version: "3.9"

services:

  db-psql:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=budgeter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  budgeter:
    build:
      context: .
      dockerfile: Dockerfile
    image: budgeter
    container_name: budgeter
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./budgeter:/app
    ports:
      - "8000:8000"
    depends_on:
      - db-psql
